name: Docker

on:
  push:
    branches:
      - main
  release:
    types:
      - published
  schedule:
    - cron:  '30 2 * * *'
  workflow_dispatch:
    inputs:
      name:
        description: 'Reason'
        required: true
        default: 'blabla...'
jobs:
  docker:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout
        uses: actions/checkout@v3

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: |
            davyinsa/rsync-server
          tags: |
            type=raw,value=latest,enable=${{ github.ref_name == 'main' }}
            type=ref,event=branch,enable=${{ github.ref_name != 'main' }}
            type=ref,event=tag
      - name: Docker meta aliyun
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: |
            davyinsa/rsync-server
          tags: |
            type=raw,value=latest,enable=${{ github.ref_name == 'main' }}
            type=ref,event=branch,enable=${{ github.ref_name != 'main' }}
            type=ref,event=tag

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        if: success() && github.event_name != 'pull_request'
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          platforms: linux/amd64,linux/arm64
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Update repo description
        uses: peter-evans/dockerhub-description@v4
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          repository: davyinsa/rsync-server
      - name: mysql server to ALIYUN CR
        id: docker_build_router_to_aliyun
        uses: docker/build-push-action@v2
        with:
          platforms: linux/amd64,linux/arm64
          push: ${{ github.event_name != 'pull_request' }}
          labels: ${{ steps.meta.outputs.labels }}
          tags: registry.cn-hangzhou.aliyuncs.com/davyin/rsync-server:${{ steps.meta.outputs.version }}
